### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by magicpencil5447** [sobhan-moosavi/DCRNN#1]
I am trying to train the DCRNN.py , however, I get the following error
OP_REQUIRES failed at conv_ops.cc:1106 : Not found: No algorithm worked!
Errors may have originated from an input operation.
Input Source operations connected to node conv2d/Conv2D:
Reshape (defined at C:/Users/VERONICA/Desktop/DCRNN-master/DCRNN.py:69)

**Comment by sobhan-moosavi** [comment]
@magicpencil5447 sorry for delayed response, were you able to figure a solution?

**Comment by magicpencil5447** [comment]
Haven't found a solution yet, but I tried to run it on the cpu and it worked
